app = "nestjs-products"
primary_region = "iad"

[http_service]
  internal_port = 3002
  auto_start_machines = true
  auto_stop_machines = "off"
  min_machines_running = 2
  force_https = true

  [http_service.concurrency]
    type = "requests"
    soft_limit = 20
    hard_limit = 25

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/api/health"
